name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out the sections below so we can reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug.
      placeholder: "When I run `optmix chat` and ask to fit a model, it crashes with..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: traceback
    attributes:
      label: Error traceback (if any)
      description: Paste the full traceback here.
      render: python

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - MMM Engine (ridge, bayesian, transforms)
        - Agents (YAML definitions, executor, orchestrator)
        - CLI (setup, chat, run)
        - Tools (data, modeling, optimization, reporting)
        - Config / LLM integration
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: OptMix version
      placeholder: "0.1.0"

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.11"
